---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: bhanunagasai/yerubandi:dbimage
   ports:
     - "3306:3306"

 application:
   container_name: appcontainer
   image: bhanunagasai/yerubandi:appimage
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
